/**
 * Signed ticket image URLs.
 * Adds a short HMAC-SHA256 token so the /i/[ticketId] route can verify
 * the link was generated by Yarro, not guessed.
 */

const APP_URL = "https://app.yarro.ai";

async function hmacSha256Short(secret: string, message: string): Promise<string> {
  const encoder = new TextEncoder();
  const key = await crypto.subtle.importKey(
    "raw",
    encoder.encode(secret),
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"],
  );
  const sig = await crypto.subtle.sign("HMAC", key, encoder.encode(message));
  // Take first 12 bytes → 16-char base64url token
  const bytes = new Uint8Array(sig).slice(0, 12);
  return btoa(String.fromCharCode(...bytes))
    .replace(/\+/g, "-")
    .replace(/\//g, "_")
    .replace(/=+$/, "");
}

function getSecret(): string {
  // Reuse the Supabase JWT secret — available in all edge functions
  const secret = Deno.env.get("SUPABASE_JWT_SECRET") || Deno.env.get("IMAGE_URL_SECRET");
  if (!secret) throw new Error("No signing secret available for image URLs");
  return secret;
}

/** Generate a signed image gallery URL for a ticket. */
export async function signedImageUrl(ticketId: string): Promise<string> {
  const token = await hmacSha256Short(getSecret(), `image:${ticketId}`);
  return `${APP_URL}/i/${ticketId}?t=${token}`;
}

/** Verify an image URL token. Returns true if valid. */
export async function verifyImageToken(ticketId: string, token: string, secret: string): Promise<boolean> {
  const expected = await hmacSha256Short(secret, `image:${ticketId}`);
  return expected === token;
}
